"""more

Revision ID: 3a3194de39d5
Revises: 7669d9c4ccf2
Create Date: 2026-02-09 08:30:08.892469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a3194de39d5'
down_revision: Union[str, None] = '7669d9c4ccf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bandit_event', sa.Column('cost_importance', sa.Integer(), nullable=True))
    op.add_column('bandit_event', sa.Column('latency_importance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bandit_event', 'latency_importance')
    op.drop_column('bandit_event', 'cost_importance')
    # ### end Alembic commands ###