"""changes

Revision ID: 7669d9c4ccf2
Revises: 
Create Date: 2026-02-08 15:06:34.168720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7669d9c4ccf2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('churned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('bandit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('experiment', 'online', name='banditmode'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('window_size', sa.Integer(), nullable=True),
    sa.Column('cost_importance', sa.Integer(), nullable=False),
    sa.Column('latency_importance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandit_user_id'), 'bandit', ['user_id'], unique=False)
    op.create_table('bandit_arm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bandit_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arm_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bandit_id'], ['bandit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandit_arm_bandit_id'), 'bandit_arm', ['bandit_id'], unique=False)
    op.create_table('bandit_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bandit_id', sa.Integer(), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('a_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('b_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('theta_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('chol_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bandit_id'], ['bandit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandit_state_bandit_id'), 'bandit_state', ['bandit_id'], unique=False)
    op.create_table('bandit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bandit_id', sa.Integer(), nullable=False),
    sa.Column('arm_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('model_score', sa.Float(), nullable=False),
    sa.Column('user_query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_output', sa.JSON(), nullable=True),
    sa.Column('immediate_reward', sa.Float(), nullable=True),
    sa.Column('human_reward', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arm_id'], ['bandit_arm.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bandit_id'], ['bandit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandit_event_bandit_id'), 'bandit_event', ['bandit_id'], unique=False)
    op.create_table('bandit_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bandit_event_id', sa.Integer(), nullable=False),
    sa.Column('segment_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('segment_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['bandit_event_id'], ['bandit_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandit_segment_bandit_event_id'), 'bandit_segment', ['bandit_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bandit_segment_bandit_event_id'), table_name='bandit_segment')
    op.drop_table('bandit_segment')
    op.drop_index(op.f('ix_bandit_event_bandit_id'), table_name='bandit_event')
    op.drop_table('bandit_event')
    op.drop_index(op.f('ix_bandit_state_bandit_id'), table_name='bandit_state')
    op.drop_table('bandit_state')
    op.drop_index(op.f('ix_bandit_arm_bandit_id'), table_name='bandit_arm')
    op.drop_table('bandit_arm')
    op.drop_index(op.f('ix_bandit_user_id'), table_name='bandit')
    op.drop_table('bandit')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###