"""changes

Revision ID: dd5c6d4fd038
Revises: 3fe937a24d9c
Create Date: 2026-01-30 15:07:51.624905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd5c6d4fd038'
down_revision: Union[str, None] = '3fe937a24d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bandit_event', sa.Column('user_query', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('bandit_event', sa.Column('llm_output', sa.JSON(), nullable=True))
    op.drop_column('bandit_event', 'has_any_reward')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bandit_event', sa.Column('has_any_reward', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('bandit_event', 'llm_output')
    op.drop_column('bandit_event', 'user_query')
    # ### end Alembic commands ###